server:
  port: 8081

spring:
  profiles:
    active: local
  jpa:
    open-in-view: false
  hibernate:
    format_sql: true
  properties:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl